### ISSUE TITLE
Build ChorusMergeModule (and ChorusHubInstaller?)

### ISSUE THREAD

**Issue by ermshiperete** [sillsdev/chorus#299]
When we moved the build to GitHub Actions building the **ChorusMergeModule** and **ChorusHubInstaller** was accidentally left out.

We should add building the ChorusMergeModule to `dotnet.yml` and save it as an artifact.

Also check if the ChorusHubInstaller is still needed - in a [discussion on slack](https://sil-language-software.slack.com/archives/C87FMEEE6/p1661434979839959?thread_ts=1661418355.194039&cid=C87FMEEE6) it was noted: 

> Looks like [ChorusHub was last released for Windows in 2018](https://software.sil.org/chorushub/download/) and the [most recent successful TC build](https://build.palaso.org/buildConfiguration/ChorusHub25WindowsServiceInstallerSansPublish) was in 2017. I don't know what the current process is, if any.
> getting rid of build/ may be safe. After so much bit rot, it may be easier to rewrite the installer from scratch if we need to.

However, it seems that `ChorusMergeModule.msm` and `ChorusHubInstaller.msi` got build as part of the regular builds (targets `Installer ChorusHubInstaller`).

Check `build/Chorus.proj` prior to commit e7ab5bcca7ae571374eb9c8d742a1975aec453f3 and [TC](https://build.palaso.org/buildConfiguration/Chorus_Win32masterContinuous?mode=builds) for how it was done in the past.

## ToDo

- [x] Add building ChorusMergeModule to `dotnet.yml`
- [x] Is ChorusHubInstaller still needed/used by anyone?
- [x] If it is, add building ChorusHubInstaller to `dotnet.yml`
- [x] document (e.g. in `dotnet.yml`) where ChorusMergeModule (and ChorusHubInstaller) is used
(in FieldWorks and FLEx Bridge installers)
- [x] (nice to have) automatically stamp copyright dates on both
- [x] Remove Build/Chorus.proj

**Comment by jasonleenaylor** [comment]
Yes we still need to be able to build the ChorusHub installer.

**Comment by papeh** [comment]
Per this article, it should be straightforward:
https://drumcoder.co.uk/blog/2022/jun/18/wix-installer-from-github-action/

**Comment by papeh** [comment]
Well, the Chorus Hub installer builds, but when I try to send to it, it fails to get the remote project.
```
Exception: The internet server reported that it is having problems. There isn't anything you can do about that except try again later.
   at Chorus.VcsDrivers.Mercurial.HgRepolitory.PullFromTarget(String targetLabel, String targetUri)
```
